name: Workflow for Actions

on:
 workflow_dispatch:
jobs:
 echo-actions:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4.6.0
      with:
        distribution: 'microsoft'
        java-version: '17'
       
